#!/bin/bash

# NeoVantis Notification Service - Quick Reference Guide
# This script shows you how to use your new notification service
echo "================================================================="
echo ""
echo "📁 What's Been Created:"
echo "   ✅ Complete NestJS notification service with email capabilities"
echo "   ✅ PostgreSQL database with proper entities and relationships"
echo "   ✅ Redis queue system for reliable email processing"
echo "   ✅ 4 built-in email templates (welcome, password-reset, email-verification, notification)"
echo "   ✅ Comprehensive API with health monitoring and statistics"
echo "   ✅ Docker setup for both development and production"
echo "   ✅ Complete documentation (API_DOCUMENTATION.md, DEPLOYMENT.md)"
echo "   ✅ Automated setup scripts (setup-dev.sh, setup-prod.sh)"
echo ""
echo "🚀 Quick Start Options:"
echo ""
echo "1️⃣  DEVELOPMENT (Docker - Recommended):"
echo "   ./setup-dev.sh"
echo ""
echo "2️⃣  DEVELOPMENT (Manual):"
echo "   npm install"
echo "   # Setup PostgreSQL and Redis"
echo "   npm run start:dev"
echo ""
echo "3️⃣  PRODUCTION:"
echo "   ./setup-prod.sh"
echo ""
echo "📧 Email Configuration:"
echo "   Your service is already configured for Mailcow!"
echo "   Host: mail.neovantis.xyz"
echo "   User: no-reply@neovantis.xyz"
echo "   Just update the password in your .env file"
echo ""
echo "🌐 Service URLs (Development):"
echo "   • Main Service: http://localhost:4321"
echo "   • Health Check: http://localhost:4321/api/v1/health"
echo "   • Redis Commander: http://localhost:8081"
echo ""
echo "📝 Quick API Tests:"
echo ""
echo "   # Send simple email"
echo "   curl -X POST http://localhost:4321/api/v1/notifications/send-email \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"to\":\"test@example.com\",\"subject\":\"Test\",\"body\":\"Hello!\"}'"
echo ""
echo "   # Send welcome template email"
echo "   curl -X POST http://localhost:4321/api/v1/notifications/send-template-email \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"to\":\"user@example.com\",\"templateName\":\"welcome\",\"variables\":{\"name\":\"John\"}}'"
echo ""
echo "   # Check service health"
echo "   curl http://localhost:4321/api/v1/health"
echo ""
echo "📚 Documentation:"
echo "   • Complete API Reference: API_DOCUMENTATION.md"
echo "   • Deployment Guide: DEPLOYMENT.md"
echo "   • Main Documentation: README.md"
echo ""
echo "🔧 Built-in Templates:"
echo "   • welcome - User onboarding emails"
echo "   • password-reset - Password reset functionality"
echo "   • email-verification - Email address verification"
echo "   • notification - General purpose notifications"
echo ""
echo "⚡ Features Included:"
echo "   • Single & bulk email sending"
echo "   • Template system with variable substitution"
echo "   • Queue processing with retry logic"
echo "   • Health monitoring and statistics"
echo "   • Audit logging for all activities"
echo "   • Docker support for easy deployment"
echo "   • Production-ready with SSL/TLS support"
echo ""
echo "🎯 Ready for Integration:"
echo "   Your notification service is ready to integrate with:"
echo "   • NeoVantis Auth Service"
echo "   • Any other NeoVantis applications"
echo "   • External services via REST API"
echo ""
echo "🚀 Next Steps:"
echo "   1. Run ./setup-dev.sh to start development environment"
echo "   2. Update MAIL_PASS in .env with your Mailcow password"
echo "   3. Test the service with the API examples above"
echo "   4. Check out the documentation for more features"
echo "   5. Start integrating with your auth service!"
echo ""
echo "🎉 Happy coding! Your notification service is production-ready!"
echo ""
