#!/bin/bash

# NeoVantis Notification Service - Production Setup Script
# This script sets up the production environment for the notification service

set -e

echo "🚀 Setting up NeoVantis Notification Service - Production Environment"
echo "====================================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Docker is installed and running
check_docker() {
    print_status "Checking Docker installation..."
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        print_error "Docker is not running. Please start Docker first."
        exit 1
    fi
    
    print_success "Docker is installed and running"
}

# Check if Docker Compose is installed
check_docker_compose() {
    print_status "Checking Docker Compose installation..."
    if ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    print_success "Docker Compose is installed"
}

# Generate secure passwords
generate_passwords() {
    print_status "Generating secure passwords..."
    
    if ! command -v openssl &> /dev/null; then
        print_error "OpenSSL is required for password generation. Please install it first."
        exit 1
    fi
    
    DB_PASSWORD=$(openssl rand -base64 32)
    REDIS_PASSWORD=$(openssl rand -base64 32)
    API_KEY=$(openssl rand -base64 32)
    
    print_success "Secure passwords generated"
}

# Create necessary directories
create_directories() {
    print_status "Creating necessary directories..."
    mkdir -p logs
    mkdir -p logs/nginx
    mkdir -p scripts
    mkdir -p config
    mkdir -p config/ssl
    print_success "Directories created"
}

# Create production environment file
create_env_file() {
    print_status "Creating production environment file..."
    
    read -p "Enter your Mailcow password for no-reply@neovantis.xyz: " -s MAIL_PASS
    echo ""
    
    read -p "Enter CORS origins (comma-separated, e.g., https://app.neovantis.xyz,https://admin.neovantis.xyz): " CORS_ORIGIN
    
    read -p "Enter Sentry DSN (optional, press enter to skip): " SENTRY_DSN
    
    cat > .env.prod << EOF
# Production Environment Configuration
# Auto-generated by setup-prod.sh

# Database Configuration
DB_PASSWORD=${DB_PASSWORD}

# Redis Configuration
REDIS_PASSWORD=${REDIS_PASSWORD}

# Email Configuration (Mailcow)
MAIL_PASS=${MAIL_PASS}

# Security Configuration
API_KEY=${API_KEY}
CORS_ORIGIN=${CORS_ORIGIN}

# Monitoring (optional)
SENTRY_DSN=${SENTRY_DSN}
EOF
    
    print_success "Production environment file created at .env.prod"
    print_warning "Keep .env.prod secure and never commit it to version control!"
}

# Create PostgreSQL configuration
create_postgres_config() {
    print_status "Creating PostgreSQL configuration..."
    
    cat > config/postgresql.conf << 'EOF'
# PostgreSQL Configuration for Production
# Optimized for performance and reliability

# Connection Settings
max_connections = 100
shared_buffers = 256MB
effective_cache_size = 1GB
work_mem = 4MB
maintenance_work_mem = 64MB

# WAL Settings
wal_buffers = 16MB
checkpoint_completion_target = 0.9
wal_level = replica

# Query Planner
random_page_cost = 1.1
effective_io_concurrency = 200

# Logging
log_destination = 'stderr'
logging_collector = on
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on

# Performance
shared_preload_libraries = 'pg_stat_statements'
track_activity_query_size = 2048
pg_stat_statements.track = all
EOF
    
    print_success "PostgreSQL configuration created"
}

# Create Redis configuration
create_redis_config() {
    print_status "Creating Redis configuration..."
    
    cat > config/redis.conf << 'EOF'
# Redis Configuration for Production
# Optimized for performance and persistence

# Network
bind 0.0.0.0
port 6379
timeout 300
tcp-keepalive 300

# Memory Management
maxmemory 512mb
maxmemory-policy allkeys-lru

# Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb

# Logging
loglevel notice
logfile /var/log/redis/redis-server.log

# Security
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command KEYS ""
rename-command CONFIG "CONFIG_b835729d"

# Performance
tcp-backlog 511
databases 16
EOF
    
    print_success "Redis configuration created"
}

# Create Nginx configuration
create_nginx_config() {
    print_status "Creating Nginx configuration..."
    
    cat > config/nginx.conf << 'EOF'
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    # Logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;
    
    # Basic Settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 16M;
    
    # Security Headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    
    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private must-revalidate max-age=0;
    gzip_types
        application/json
        application/javascript
        application/xml+rss
        application/atom+xml
        image/svg+xml
        text/plain
        text/css
        text/js
        text/xml
        text/javascript;
    
    # Rate Limiting
    limit_req_zone $binary_remote_addr zone=api:10m rate=1000r/h;
    
    # Upstream
    upstream notification_service {
        server app:4321 max_fails=3 fail_timeout=30s;
    }
    
    # HTTP Server (redirect to HTTPS)
    server {
        listen 80;
        server_name notifications.neovantis.xyz;
        return 301 https://$server_name$request_uri;
    }
    
    # HTTPS Server
    server {
        listen 443 ssl http2;
        server_name notifications.neovantis.xyz;
        
        # SSL Configuration
        ssl_certificate /etc/ssl/certs/neovantis.xyz.crt;
        ssl_certificate_key /etc/ssl/private/neovantis.xyz.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        
        # API Routes
        location / {
            limit_req zone=api burst=20 nodelay;
            
            proxy_pass http://notification_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeouts
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
            
            # Health check bypass
            if ($request_uri = "/api/v1/health/simple") {
                access_log off;
            }
        }
        
        # Health check endpoint (no rate limiting)
        location /api/v1/health {
            proxy_pass http://notification_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            access_log off;
        }
    }
}
EOF
    
    print_success "Nginx configuration created"
    print_warning "Please place your SSL certificates in config/ssl/ directory"
}

# Create database initialization script
create_db_init_script() {
    print_status "Creating database initialization script..."
    
    cat > scripts/init-db.sql << 'EOF'
-- Database initialization script for NeoVantis Notification Service (Production)
-- This script sets up the database with proper permissions

-- Create extensions if they don't exist
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Grant necessary permissions
GRANT ALL PRIVILEGES ON DATABASE notifications_prod TO notifications_user;

-- Create additional indexes for performance
-- These will be created by TypeORM migrations, but can be added here if needed
EOF
    
    print_success "Database initialization script created"
}

# Create backup script
create_backup_script() {
    print_status "Creating backup script..."
    
    cat > scripts/backup-db.sh << 'EOF'
#!/bin/bash

# Database backup script for NeoVantis Notification Service

BACKUP_DIR="/opt/backups/notifications"
DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="notifications_backup_${DATE}.sql"

# Create backup directory if it doesn't exist
mkdir -p ${BACKUP_DIR}

# Perform backup
docker exec notifications_postgres_prod pg_dump -U notifications_user notifications_prod > ${BACKUP_DIR}/${BACKUP_FILE}

# Compress backup
gzip ${BACKUP_DIR}/${BACKUP_FILE}

# Remove backups older than 30 days
find ${BACKUP_DIR} -name "*.gz" -mtime +30 -delete

echo "Backup completed: ${BACKUP_DIR}/${BACKUP_FILE}.gz"
EOF
    
    chmod +x scripts/backup-db.sh
    print_success "Backup script created at scripts/backup-db.sh"
}

# Build and start services
start_services() {
    print_status "Building and starting production services..."
    
    # Load environment variables
    export $(cat .env.prod | grep -v '^#' | xargs)
    
    # Build and start services
    docker-compose -f docker-compose.prod.yml up -d --build
    
    print_success "Services started successfully"
}

# Wait for services to be healthy
wait_for_services() {
    print_status "Waiting for services to be ready..."
    
    # Wait for PostgreSQL
    print_status "Waiting for PostgreSQL..."
    until docker exec notifications_postgres_prod pg_isready -U notifications_user -d notifications_prod; do
        sleep 2
    done
    print_success "PostgreSQL is ready"
    
    # Wait for Redis
    print_status "Waiting for Redis..."
    until docker exec notifications_redis_prod redis-cli --no-auth-warning -a ${REDIS_PASSWORD} ping; do
        sleep 2
    done
    print_success "Redis is ready"
    
    # Wait for application
    print_status "Waiting for Notification Service..."
    for i in {1..30}; do
        if curl -s http://localhost:4321/api/v1/health/simple > /dev/null; then
            print_success "Notification Service is ready"
            break
        fi
        if [ $i -eq 30 ]; then
            print_error "Timeout waiting for Notification Service"
            exit 1
        fi
        sleep 3
    done
}

# Run database migrations
run_migrations() {
    print_status "Running database migrations..."
    docker exec notifications_app_prod npm run migration:run
    print_success "Database migrations completed"
}

# Setup log rotation
setup_log_rotation() {
    print_status "Setting up log rotation..."
    
    cat > /etc/logrotate.d/notifications << EOF
/path/to/NotificationService/logs/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 644 root root
    postrotate
        docker kill --signal="USR1" notifications_app_prod 2>/dev/null || true
    endscript
}
EOF
    
    print_success "Log rotation configured"
}

# Setup monitoring cron jobs
setup_cron_jobs() {
    print_status "Setting up monitoring cron jobs..."
    
    # Create cron jobs for production monitoring
    (crontab -l 2>/dev/null; echo "0 2 * * * /path/to/NotificationService/scripts/backup-db.sh") | crontab -
    (crontab -l 2>/dev/null; echo "*/5 * * * * curl -s http://localhost:4321/api/v1/health/simple > /dev/null || echo 'Service down' | mail -s 'Notification Service Alert' admin@neovantis.xyz") | crontab -
    
    print_success "Cron jobs configured"
}

# Display service information
display_info() {
    echo ""
    echo "====================================================================="
    print_success "Production environment setup completed!"
    echo "====================================================================="
    echo ""
    echo "🌐 Service URLs:"
    echo "   • HTTPS: https://notifications.neovantis.xyz"
    echo "   • HTTP (redirects): http://notifications.neovantis.xyz"
    echo "   • Health Check: https://notifications.neovantis.xyz/api/v1/health"
    echo ""
    echo "🔐 Security Information:"
    echo "   • Database Password: [stored in .env.prod]"
    echo "   • Redis Password: [stored in .env.prod]"
    echo "   • API Key: [stored in .env.prod]"
    echo ""
    echo "📝 Important Files:"
    echo "   • Environment: .env.prod (keep secure!)"
    echo "   • SSL Certificates: config/ssl/"
    echo "   • Logs: logs/"
    echo "   • Backups: scripts/backup-db.sh"
    echo ""
    echo "🔧 Management Commands:"
    echo "   • View logs: docker-compose -f docker-compose.prod.yml logs -f"
    echo "   • Stop services: docker-compose -f docker-compose.prod.yml down"
    echo "   • Restart app: docker-compose -f docker-compose.prod.yml restart app"
    echo "   • Backup database: ./scripts/backup-db.sh"
    echo ""
    echo "📊 Monitoring:"
    echo "   • Health endpoint monitoring configured"
    echo "   • Daily database backups scheduled"
    echo "   • Log rotation configured"
    echo ""
    echo "⚠️  Next Steps:"
    echo "   1. Place SSL certificates in config/ssl/"
    echo "   2. Configure your domain DNS to point to this server"
    echo "   3. Test the service thoroughly"
    echo "   4. Set up external monitoring (optional)"
    echo ""
}

# Main execution
main() {
    echo "Starting production environment setup..."
    echo ""
    
    print_warning "This script will set up a production environment with secure passwords."
    print_warning "Make sure you're running this on a production server."
    read -p "Continue? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_error "Setup cancelled."
        exit 1
    fi
    
    check_docker
    check_docker_compose
    generate_passwords
    create_directories
    create_env_file
    create_postgres_config
    create_redis_config
    create_nginx_config
    create_db_init_script
    create_backup_script
    start_services
    wait_for_services
    run_migrations
    setup_log_rotation
    setup_cron_jobs
    display_info
    
    print_success "Production setup completed successfully! 🎉"
}

# Handle script interruption
trap 'print_error "Setup interrupted. You may need to clean up Docker containers manually."; exit 1' INT

# Run main function
main "$@"
