#!/bin/bash

# NeoVantis Notification Service - Development Setup Script
# This script sets up the development environment for the notification service

set -e

echo "🚀 Setting up NeoVantis Notification Service - Development Environment"
echo "=================================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Docker is installed and running
check_docker() {
    print_status "Checking Docker installation..."
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    if ! docker info &> /dev/null; then
        print_error "Docker is not running. Please start Docker first."
        exit 1
    fi
    
    print_success "Docker is installed and running"
}

# Check if Docker Compose is installed
check_docker_compose() {
    print_status "Checking Docker Compose installation..."
    if ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    print_success "Docker Compose is installed"
}

# Create necessary directories
create_directories() {
    print_status "Creating necessary directories..."
    mkdir -p logs
    mkdir -p scripts
    mkdir -p config
    print_success "Directories created"
}

# Create environment file for development
create_env_file() {
    print_status "Creating development environment file..."
    
    if [ ! -f .env.dev ]; then
        cat > .env.dev << EOF
# Development Environment Configuration
# Auto-generated by setup-dev.sh

# Database Configuration
DB_HOST=postgres
DB_PORT=5432
DB_NAME=notifications_dev
DB_USERNAME=notifications_user
DB_PASSWORD=dev_password_123

# Redis Configuration
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Email Configuration (Mailcow)
# Update MAIL_PASS with your actual Mailcow password
MAIL_HOST=mail.neovantis.xyz
MAIL_PORT=465
MAIL_SECURE=true
MAIL_USER=no-reply@neovantis.xyz
MAIL_PASS=your_mailcow_password_here

# Application Configuration
NODE_ENV=development
PORT=4321
LOG_LEVEL=debug

# Queue Configuration
QUEUE_REDIS_HOST=redis
QUEUE_REDIS_PORT=6379
QUEUE_REDIS_DB=1
EOF
        print_success "Environment file created at .env.dev"
        print_warning "Please update MAIL_PASS in .env.dev with your actual Mailcow password"
    else
        print_warning ".env.dev already exists, skipping creation"
    fi
}

# Create database initialization script
create_db_init_script() {
    print_status "Creating database initialization script..."
    
    if [ ! -f scripts/init-db.sql ]; then
        cat > scripts/init-db.sql << 'EOF'
-- Database initialization script for NeoVantis Notification Service
-- This script sets up the database with proper permissions

-- Create extensions if they don't exist
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Grant necessary permissions
GRANT ALL PRIVILEGES ON DATABASE notifications_dev TO notifications_user;
GRANT ALL PRIVILEGES ON DATABASE notifications_prod TO notifications_user;

-- Create schemas if needed
-- Additional initialization can be added here
EOF
        print_success "Database initialization script created"
    else
        print_warning "Database initialization script already exists"
    fi
}

# Install Node.js dependencies
install_dependencies() {
    print_status "Installing Node.js dependencies..."
    
    if [ -f package.json ]; then
        npm install
        print_success "Dependencies installed successfully"
    else
        print_error "package.json not found. Make sure you're in the correct directory."
        exit 1
    fi
}

# Build and start services
start_services() {
    print_status "Building and starting development services..."
    
    # Load environment variables
    export $(cat .env.dev | grep -v '^#' | xargs)
    
    # Build and start services
    docker-compose -f docker-compose.dev.yml up -d --build
    
    print_success "Services started successfully"
}

# Wait for services to be healthy
wait_for_services() {
    print_status "Waiting for services to be ready..."
    
    # Wait for PostgreSQL
    print_status "Waiting for PostgreSQL..."
    until docker exec notifications_postgres_dev pg_isready -U notifications_user -d notifications_dev; do
        sleep 2
    done
    print_success "PostgreSQL is ready"
    
    # Wait for Redis
    print_status "Waiting for Redis..."
    until docker exec notifications_redis_dev redis-cli ping; do
        sleep 2
    done
    print_success "Redis is ready"
    
    # Wait for application
    print_status "Waiting for Notification Service..."
    for i in {1..30}; do
        if curl -s http://localhost:4321/api/v1/health/simple > /dev/null; then
            print_success "Notification Service is ready"
            break
        fi
        if [ $i -eq 30 ]; then
            print_error "Timeout waiting for Notification Service"
            exit 1
        fi
        sleep 3
    done
}

# Run database migrations
run_migrations() {
    print_status "Running database migrations..."
    docker exec notifications_app_dev npm run migration:run
    print_success "Database migrations completed"
}

# Display service information
display_info() {
    echo ""
    echo "=================================================================="
    print_success "Development environment setup completed!"
    echo "=================================================================="
    echo ""
    echo "🌐 Service URLs:"
    echo "   • Notification Service: http://localhost:4321"
    echo "   • API Health Check: http://localhost:4321/api/v1/health"
    echo "   • Redis Commander: http://localhost:8081"
    echo ""
    echo "🗄️  Database Connection:"
    echo "   • Host: localhost"
    echo "   • Port: 5432"
    echo "   • Database: notifications_dev"
    echo "   • Username: notifications_user"
    echo "   • Password: dev_password_123"
    echo ""
    echo "📊 Redis Connection:"
    echo "   • Host: localhost"
    echo "   • Port: 6379"
    echo "   • No password required"
    echo ""
    echo "📝 Useful Commands:"
    echo "   • View logs: docker-compose -f docker-compose.dev.yml logs -f"
    echo "   • Stop services: docker-compose -f docker-compose.dev.yml down"
    echo "   • Restart app: docker-compose -f docker-compose.dev.yml restart app"
    echo "   • Enter app container: docker exec -it notifications_app_dev sh"
    echo ""
    echo "📧 Email Configuration:"
    print_warning "Don't forget to update MAIL_PASS in .env.dev with your Mailcow password!"
    echo ""
    echo "🔧 Development Tools:"
    echo "   • Hot reload is enabled for code changes"
    echo "   • Debug logging is enabled"
    echo "   • Redis Commander available for queue monitoring"
    echo ""
}

# Main execution
main() {
    echo "Starting development environment setup..."
    echo ""
    
    check_docker
    check_docker_compose
    create_directories
    create_env_file
    create_db_init_script
    install_dependencies
    start_services
    wait_for_services
    run_migrations
    display_info
    
    print_success "Setup completed successfully! 🎉"
}

# Handle script interruption
trap 'print_error "Setup interrupted. You may need to clean up Docker containers manually."; exit 1' INT

# Run main function
main "$@"
